import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="glass grid min-h-screen place-items-center bg-gradient-to-b from-customBackground via-customBackground to-customBackground/90 py-8">
        {children}
      </body>
    </html>
  );
}
